[package]
name = "rust_crates_lab"
version = "0.1.0"
edition = "2024"
description = "A simple Rust project to explore crates, modules, and packaging."
license = "MIT"
repository = "https://github.com/abu166/Introduction_To_Rust.git"

[dependencies]
rand = "0.8"
